name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: stop docker container the Docker image
      continue-on-error: true
      run: docker container rm -f mypythonapp
      
    - name: start docker container the Docker image
      continue-on-error: true
      run: docker run -p 5000:5000 --name mypythonapp my-image-name:$(date +%s)
