name: Docker Image CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localhost:4000/my-image-name:$(date +%s) 
    - name: stop docker container the Docker image
      continue-on-error: true
      run: docker container rm -f mypythonapp
      
    - name: push docker container the Docker image
      continue-on-error: true
      run: docker push localhost:4000/my-image-name:$(date +%s)
   
    - name: start docker container the Docker image
      continue-on-error: true
      run: docker run -p -d 5000:5000 --name mypythonapp localhost:4000/my-image-name:$(date +%s)
